# Usa uma imagem oficial do Python
FROM python:3.11

# Define o diretório de trabalho dentro do contêiner
WORKDIR /scheduling

# Copia os arquivos do projeto para dentro do contêiner
COPY requirements.txt .

# Instala dependências do sistema
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todos os arquivos do projeto
COPY . .

# Expõe a porta 8000 
EXPOSE 8000

# Comando padrão ao iniciar o contêiner
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "appointment_scheduling.wsgi:application"]
