FROM python:3.11

WORKDIR /scheduling

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .
 
EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "appointment_scheduling.wsgi:application"]
